// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/protobuf/message.proto

package xyz.shiqihao.misc.protobuf;

public final class ProtobufMessage {
  private ProtobufMessage() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface MessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:protobuf.Message)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string id = 1;</code>
     */
    java.lang.String getId();
    /**
     * <code>string id = 1;</code>
     */
    com.google.protobuf.ByteString
        getIdBytes();

    /**
     * <code>string sign_name = 2;</code>
     */
    java.lang.String getSignName();
    /**
     * <code>string sign_name = 2;</code>
     */
    com.google.protobuf.ByteString
        getSignNameBytes();

    /**
     * <code>repeated string template = 3;</code>
     */
    java.util.List<java.lang.String>
        getTemplateList();
    /**
     * <code>repeated string template = 3;</code>
     */
    int getTemplateCount();
    /**
     * <code>repeated string template = 3;</code>
     */
    java.lang.String getTemplate(int index);
    /**
     * <code>repeated string template = 3;</code>
     */
    com.google.protobuf.ByteString
        getTemplateBytes(int index);

    /**
     * <code>string receiver = 4;</code>
     */
    java.lang.String getReceiver();
    /**
     * <code>string receiver = 4;</code>
     */
    com.google.protobuf.ByteString
        getReceiverBytes();

    /**
     * <code>string areaCode = 5;</code>
     */
    java.lang.String getAreaCode();
    /**
     * <code>string areaCode = 5;</code>
     */
    com.google.protobuf.ByteString
        getAreaCodeBytes();

    /**
     * <code>map&lt;string, string&gt; parameters = 6;</code>
     */
    int getParametersCount();
    /**
     * <code>map&lt;string, string&gt; parameters = 6;</code>
     */
    boolean containsParameters(
        java.lang.String key);
    /**
     * Use {@link #getParametersMap()} instead.
     */
    @java.lang.Deprecated
    java.util.Map<java.lang.String, java.lang.String>
    getParameters();
    /**
     * <code>map&lt;string, string&gt; parameters = 6;</code>
     */
    java.util.Map<java.lang.String, java.lang.String>
    getParametersMap();
    /**
     * <code>map&lt;string, string&gt; parameters = 6;</code>
     */

    java.lang.String getParametersOrDefault(
        java.lang.String key,
        java.lang.String defaultValue);
    /**
     * <code>map&lt;string, string&gt; parameters = 6;</code>
     */

    java.lang.String getParametersOrThrow(
        java.lang.String key);

    /**
     * <code>int64 created = 7;</code>
     */
    long getCreated();

    /**
     * <code>int32 expires = 8;</code>
     */
    int getExpires();

    /**
     * <code>.protobuf.Message.SmsProvider sms_provider = 9;</code>
     */
    int getSmsProviderValue();
    /**
     * <code>.protobuf.Message.SmsProvider sms_provider = 9;</code>
     */
    xyz.shiqihao.misc.protobuf.ProtobufMessage.Message.SmsProvider getSmsProvider();

    /**
     * <code>string provider_key = 10;</code>
     */
    java.lang.String getProviderKey();
    /**
     * <code>string provider_key = 10;</code>
     */
    com.google.protobuf.ByteString
        getProviderKeyBytes();

    /**
     * <code>string provider_value = 12;</code>
     */
    java.lang.String getProviderValue();
    /**
     * <code>string provider_value = 12;</code>
     */
    com.google.protobuf.ByteString
        getProviderValueBytes();

    /**
     * <pre>
     * 请求供应商的地址,部分厂商需要设置.
     * </pre>
     *
     * <code>string send_path = 13;</code>
     */
    java.lang.String getSendPath();
    /**
     * <pre>
     * 请求供应商的地址,部分厂商需要设置.
     * </pre>
     *
     * <code>string send_path = 13;</code>
     */
    com.google.protobuf.ByteString
        getSendPathBytes();

    /**
     * <pre>
     * 短信模板中的变量,部分厂商需要
     * </pre>
     *
     * <code>string template_param = 14;</code>
     */
    java.lang.String getTemplateParam();
    /**
     * <pre>
     * 短信模板中的变量,部分厂商需要
     * </pre>
     *
     * <code>string template_param = 14;</code>
     */
    com.google.protobuf.ByteString
        getTemplateParamBytes();
  }
  /**
   * Protobuf type {@code protobuf.Message}
   */
  public  static final class Message extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:protobuf.Message)
      MessageOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Message.newBuilder() to construct.
    private Message(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Message() {
      id_ = "";
      signName_ = "";
      template_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      receiver_ = "";
      areaCode_ = "";
      smsProvider_ = 0;
      providerKey_ = "";
      providerValue_ = "";
      sendPath_ = "";
      templateParam_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Message(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              id_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              signName_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();
              if (!((mutable_bitField0_ & 0x00000004) != 0)) {
                template_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000004;
              }
              template_.add(s);
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              receiver_ = s;
              break;
            }
            case 42: {
              java.lang.String s = input.readStringRequireUtf8();

              areaCode_ = s;
              break;
            }
            case 50: {
              if (!((mutable_bitField0_ & 0x00000020) != 0)) {
                parameters_ = com.google.protobuf.MapField.newMapField(
                    ParametersDefaultEntryHolder.defaultEntry);
                mutable_bitField0_ |= 0x00000020;
              }
              com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
              parameters__ = input.readMessage(
                  ParametersDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
              parameters_.getMutableMap().put(
                  parameters__.getKey(), parameters__.getValue());
              break;
            }
            case 56: {

              created_ = input.readInt64();
              break;
            }
            case 64: {

              expires_ = input.readInt32();
              break;
            }
            case 72: {
              int rawValue = input.readEnum();

              smsProvider_ = rawValue;
              break;
            }
            case 82: {
              java.lang.String s = input.readStringRequireUtf8();

              providerKey_ = s;
              break;
            }
            case 98: {
              java.lang.String s = input.readStringRequireUtf8();

              providerValue_ = s;
              break;
            }
            case 106: {
              java.lang.String s = input.readStringRequireUtf8();

              sendPath_ = s;
              break;
            }
            case 114: {
              java.lang.String s = input.readStringRequireUtf8();

              templateParam_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000004) != 0)) {
          template_ = template_.getUnmodifiableView();
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return xyz.shiqihao.misc.protobuf.ProtobufMessage.internal_static_protobuf_Message_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    @java.lang.Override
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 6:
          return internalGetParameters();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return xyz.shiqihao.misc.protobuf.ProtobufMessage.internal_static_protobuf_Message_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              xyz.shiqihao.misc.protobuf.ProtobufMessage.Message.class, xyz.shiqihao.misc.protobuf.ProtobufMessage.Message.Builder.class);
    }

    /**
     * Protobuf enum {@code protobuf.Message.SmsProvider}
     */
    public enum SmsProvider
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>ALIYUN = 0;</code>
       */
      ALIYUN(0),
      /**
       * <code>YUNPIAN = 1;</code>
       */
      YUNPIAN(1),
      /**
       * <code>CHUANGLAN = 2;</code>
       */
      CHUANGLAN(2),
      UNRECOGNIZED(-1),
      ;

      /**
       * <code>ALIYUN = 0;</code>
       */
      public static final int ALIYUN_VALUE = 0;
      /**
       * <code>YUNPIAN = 1;</code>
       */
      public static final int YUNPIAN_VALUE = 1;
      /**
       * <code>CHUANGLAN = 2;</code>
       */
      public static final int CHUANGLAN_VALUE = 2;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static SmsProvider valueOf(int value) {
        return forNumber(value);
      }

      public static SmsProvider forNumber(int value) {
        switch (value) {
          case 0: return ALIYUN;
          case 1: return YUNPIAN;
          case 2: return CHUANGLAN;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<SmsProvider>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          SmsProvider> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<SmsProvider>() {
              public SmsProvider findValueByNumber(int number) {
                return SmsProvider.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return xyz.shiqihao.misc.protobuf.ProtobufMessage.Message.getDescriptor().getEnumTypes().get(0);
      }

      private static final SmsProvider[] VALUES = values();

      public static SmsProvider valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private SmsProvider(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:protobuf.Message.SmsProvider)
    }

    private int bitField0_;
    public static final int ID_FIELD_NUMBER = 1;
    private volatile java.lang.Object id_;
    /**
     * <code>string id = 1;</code>
     */
    public java.lang.String getId() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        id_ = s;
        return s;
      }
    }
    /**
     * <code>string id = 1;</code>
     */
    public com.google.protobuf.ByteString
        getIdBytes() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SIGN_NAME_FIELD_NUMBER = 2;
    private volatile java.lang.Object signName_;
    /**
     * <code>string sign_name = 2;</code>
     */
    public java.lang.String getSignName() {
      java.lang.Object ref = signName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        signName_ = s;
        return s;
      }
    }
    /**
     * <code>string sign_name = 2;</code>
     */
    public com.google.protobuf.ByteString
        getSignNameBytes() {
      java.lang.Object ref = signName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        signName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TEMPLATE_FIELD_NUMBER = 3;
    private com.google.protobuf.LazyStringList template_;
    /**
     * <code>repeated string template = 3;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getTemplateList() {
      return template_;
    }
    /**
     * <code>repeated string template = 3;</code>
     */
    public int getTemplateCount() {
      return template_.size();
    }
    /**
     * <code>repeated string template = 3;</code>
     */
    public java.lang.String getTemplate(int index) {
      return template_.get(index);
    }
    /**
     * <code>repeated string template = 3;</code>
     */
    public com.google.protobuf.ByteString
        getTemplateBytes(int index) {
      return template_.getByteString(index);
    }

    public static final int RECEIVER_FIELD_NUMBER = 4;
    private volatile java.lang.Object receiver_;
    /**
     * <code>string receiver = 4;</code>
     */
    public java.lang.String getReceiver() {
      java.lang.Object ref = receiver_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        receiver_ = s;
        return s;
      }
    }
    /**
     * <code>string receiver = 4;</code>
     */
    public com.google.protobuf.ByteString
        getReceiverBytes() {
      java.lang.Object ref = receiver_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        receiver_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int AREACODE_FIELD_NUMBER = 5;
    private volatile java.lang.Object areaCode_;
    /**
     * <code>string areaCode = 5;</code>
     */
    public java.lang.String getAreaCode() {
      java.lang.Object ref = areaCode_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        areaCode_ = s;
        return s;
      }
    }
    /**
     * <code>string areaCode = 5;</code>
     */
    public com.google.protobuf.ByteString
        getAreaCodeBytes() {
      java.lang.Object ref = areaCode_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        areaCode_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PARAMETERS_FIELD_NUMBER = 6;
    private static final class ParametersDefaultEntryHolder {
      static final com.google.protobuf.MapEntry<
          java.lang.String, java.lang.String> defaultEntry =
              com.google.protobuf.MapEntry
              .<java.lang.String, java.lang.String>newDefaultInstance(
                  xyz.shiqihao.misc.protobuf.ProtobufMessage.internal_static_protobuf_Message_ParametersEntry_descriptor, 
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "",
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "");
    }
    private com.google.protobuf.MapField<
        java.lang.String, java.lang.String> parameters_;
    private com.google.protobuf.MapField<java.lang.String, java.lang.String>
    internalGetParameters() {
      if (parameters_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            ParametersDefaultEntryHolder.defaultEntry);
      }
      return parameters_;
    }

    public int getParametersCount() {
      return internalGetParameters().getMap().size();
    }
    /**
     * <code>map&lt;string, string&gt; parameters = 6;</code>
     */

    public boolean containsParameters(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      return internalGetParameters().getMap().containsKey(key);
    }
    /**
     * Use {@link #getParametersMap()} instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.String> getParameters() {
      return getParametersMap();
    }
    /**
     * <code>map&lt;string, string&gt; parameters = 6;</code>
     */

    public java.util.Map<java.lang.String, java.lang.String> getParametersMap() {
      return internalGetParameters().getMap();
    }
    /**
     * <code>map&lt;string, string&gt; parameters = 6;</code>
     */

    public java.lang.String getParametersOrDefault(
        java.lang.String key,
        java.lang.String defaultValue) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetParameters().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;string, string&gt; parameters = 6;</code>
     */

    public java.lang.String getParametersOrThrow(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetParameters().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }

    public static final int CREATED_FIELD_NUMBER = 7;
    private long created_;
    /**
     * <code>int64 created = 7;</code>
     */
    public long getCreated() {
      return created_;
    }

    public static final int EXPIRES_FIELD_NUMBER = 8;
    private int expires_;
    /**
     * <code>int32 expires = 8;</code>
     */
    public int getExpires() {
      return expires_;
    }

    public static final int SMS_PROVIDER_FIELD_NUMBER = 9;
    private int smsProvider_;
    /**
     * <code>.protobuf.Message.SmsProvider sms_provider = 9;</code>
     */
    public int getSmsProviderValue() {
      return smsProvider_;
    }
    /**
     * <code>.protobuf.Message.SmsProvider sms_provider = 9;</code>
     */
    public xyz.shiqihao.misc.protobuf.ProtobufMessage.Message.SmsProvider getSmsProvider() {
      @SuppressWarnings("deprecation")
      xyz.shiqihao.misc.protobuf.ProtobufMessage.Message.SmsProvider result = xyz.shiqihao.misc.protobuf.ProtobufMessage.Message.SmsProvider.valueOf(smsProvider_);
      return result == null ? xyz.shiqihao.misc.protobuf.ProtobufMessage.Message.SmsProvider.UNRECOGNIZED : result;
    }

    public static final int PROVIDER_KEY_FIELD_NUMBER = 10;
    private volatile java.lang.Object providerKey_;
    /**
     * <code>string provider_key = 10;</code>
     */
    public java.lang.String getProviderKey() {
      java.lang.Object ref = providerKey_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        providerKey_ = s;
        return s;
      }
    }
    /**
     * <code>string provider_key = 10;</code>
     */
    public com.google.protobuf.ByteString
        getProviderKeyBytes() {
      java.lang.Object ref = providerKey_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        providerKey_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PROVIDER_VALUE_FIELD_NUMBER = 12;
    private volatile java.lang.Object providerValue_;
    /**
     * <code>string provider_value = 12;</code>
     */
    public java.lang.String getProviderValue() {
      java.lang.Object ref = providerValue_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        providerValue_ = s;
        return s;
      }
    }
    /**
     * <code>string provider_value = 12;</code>
     */
    public com.google.protobuf.ByteString
        getProviderValueBytes() {
      java.lang.Object ref = providerValue_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        providerValue_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SEND_PATH_FIELD_NUMBER = 13;
    private volatile java.lang.Object sendPath_;
    /**
     * <pre>
     * 请求供应商的地址,部分厂商需要设置.
     * </pre>
     *
     * <code>string send_path = 13;</code>
     */
    public java.lang.String getSendPath() {
      java.lang.Object ref = sendPath_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        sendPath_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 请求供应商的地址,部分厂商需要设置.
     * </pre>
     *
     * <code>string send_path = 13;</code>
     */
    public com.google.protobuf.ByteString
        getSendPathBytes() {
      java.lang.Object ref = sendPath_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        sendPath_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TEMPLATE_PARAM_FIELD_NUMBER = 14;
    private volatile java.lang.Object templateParam_;
    /**
     * <pre>
     * 短信模板中的变量,部分厂商需要
     * </pre>
     *
     * <code>string template_param = 14;</code>
     */
    public java.lang.String getTemplateParam() {
      java.lang.Object ref = templateParam_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        templateParam_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 短信模板中的变量,部分厂商需要
     * </pre>
     *
     * <code>string template_param = 14;</code>
     */
    public com.google.protobuf.ByteString
        getTemplateParamBytes() {
      java.lang.Object ref = templateParam_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        templateParam_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, id_);
      }
      if (!getSignNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, signName_);
      }
      for (int i = 0; i < template_.size(); i++) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, template_.getRaw(i));
      }
      if (!getReceiverBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, receiver_);
      }
      if (!getAreaCodeBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, areaCode_);
      }
      com.google.protobuf.GeneratedMessageV3
        .serializeStringMapTo(
          output,
          internalGetParameters(),
          ParametersDefaultEntryHolder.defaultEntry,
          6);
      if (created_ != 0L) {
        output.writeInt64(7, created_);
      }
      if (expires_ != 0) {
        output.writeInt32(8, expires_);
      }
      if (smsProvider_ != xyz.shiqihao.misc.protobuf.ProtobufMessage.Message.SmsProvider.ALIYUN.getNumber()) {
        output.writeEnum(9, smsProvider_);
      }
      if (!getProviderKeyBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 10, providerKey_);
      }
      if (!getProviderValueBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 12, providerValue_);
      }
      if (!getSendPathBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 13, sendPath_);
      }
      if (!getTemplateParamBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 14, templateParam_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, id_);
      }
      if (!getSignNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, signName_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < template_.size(); i++) {
          dataSize += computeStringSizeNoTag(template_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getTemplateList().size();
      }
      if (!getReceiverBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, receiver_);
      }
      if (!getAreaCodeBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, areaCode_);
      }
      for (java.util.Map.Entry<java.lang.String, java.lang.String> entry
           : internalGetParameters().getMap().entrySet()) {
        com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
        parameters__ = ParametersDefaultEntryHolder.defaultEntry.newBuilderForType()
            .setKey(entry.getKey())
            .setValue(entry.getValue())
            .build();
        size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(6, parameters__);
      }
      if (created_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(7, created_);
      }
      if (expires_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(8, expires_);
      }
      if (smsProvider_ != xyz.shiqihao.misc.protobuf.ProtobufMessage.Message.SmsProvider.ALIYUN.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(9, smsProvider_);
      }
      if (!getProviderKeyBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(10, providerKey_);
      }
      if (!getProviderValueBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(12, providerValue_);
      }
      if (!getSendPathBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(13, sendPath_);
      }
      if (!getTemplateParamBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(14, templateParam_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof xyz.shiqihao.misc.protobuf.ProtobufMessage.Message)) {
        return super.equals(obj);
      }
      xyz.shiqihao.misc.protobuf.ProtobufMessage.Message other = (xyz.shiqihao.misc.protobuf.ProtobufMessage.Message) obj;

      if (!getId()
          .equals(other.getId())) return false;
      if (!getSignName()
          .equals(other.getSignName())) return false;
      if (!getTemplateList()
          .equals(other.getTemplateList())) return false;
      if (!getReceiver()
          .equals(other.getReceiver())) return false;
      if (!getAreaCode()
          .equals(other.getAreaCode())) return false;
      if (!internalGetParameters().equals(
          other.internalGetParameters())) return false;
      if (getCreated()
          != other.getCreated()) return false;
      if (getExpires()
          != other.getExpires()) return false;
      if (smsProvider_ != other.smsProvider_) return false;
      if (!getProviderKey()
          .equals(other.getProviderKey())) return false;
      if (!getProviderValue()
          .equals(other.getProviderValue())) return false;
      if (!getSendPath()
          .equals(other.getSendPath())) return false;
      if (!getTemplateParam()
          .equals(other.getTemplateParam())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId().hashCode();
      hash = (37 * hash) + SIGN_NAME_FIELD_NUMBER;
      hash = (53 * hash) + getSignName().hashCode();
      if (getTemplateCount() > 0) {
        hash = (37 * hash) + TEMPLATE_FIELD_NUMBER;
        hash = (53 * hash) + getTemplateList().hashCode();
      }
      hash = (37 * hash) + RECEIVER_FIELD_NUMBER;
      hash = (53 * hash) + getReceiver().hashCode();
      hash = (37 * hash) + AREACODE_FIELD_NUMBER;
      hash = (53 * hash) + getAreaCode().hashCode();
      if (!internalGetParameters().getMap().isEmpty()) {
        hash = (37 * hash) + PARAMETERS_FIELD_NUMBER;
        hash = (53 * hash) + internalGetParameters().hashCode();
      }
      hash = (37 * hash) + CREATED_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getCreated());
      hash = (37 * hash) + EXPIRES_FIELD_NUMBER;
      hash = (53 * hash) + getExpires();
      hash = (37 * hash) + SMS_PROVIDER_FIELD_NUMBER;
      hash = (53 * hash) + smsProvider_;
      hash = (37 * hash) + PROVIDER_KEY_FIELD_NUMBER;
      hash = (53 * hash) + getProviderKey().hashCode();
      hash = (37 * hash) + PROVIDER_VALUE_FIELD_NUMBER;
      hash = (53 * hash) + getProviderValue().hashCode();
      hash = (37 * hash) + SEND_PATH_FIELD_NUMBER;
      hash = (53 * hash) + getSendPath().hashCode();
      hash = (37 * hash) + TEMPLATE_PARAM_FIELD_NUMBER;
      hash = (53 * hash) + getTemplateParam().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static xyz.shiqihao.misc.protobuf.ProtobufMessage.Message parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static xyz.shiqihao.misc.protobuf.ProtobufMessage.Message parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static xyz.shiqihao.misc.protobuf.ProtobufMessage.Message parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static xyz.shiqihao.misc.protobuf.ProtobufMessage.Message parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static xyz.shiqihao.misc.protobuf.ProtobufMessage.Message parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static xyz.shiqihao.misc.protobuf.ProtobufMessage.Message parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static xyz.shiqihao.misc.protobuf.ProtobufMessage.Message parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static xyz.shiqihao.misc.protobuf.ProtobufMessage.Message parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static xyz.shiqihao.misc.protobuf.ProtobufMessage.Message parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static xyz.shiqihao.misc.protobuf.ProtobufMessage.Message parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static xyz.shiqihao.misc.protobuf.ProtobufMessage.Message parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static xyz.shiqihao.misc.protobuf.ProtobufMessage.Message parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(xyz.shiqihao.misc.protobuf.ProtobufMessage.Message prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code protobuf.Message}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:protobuf.Message)
        xyz.shiqihao.misc.protobuf.ProtobufMessage.MessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return xyz.shiqihao.misc.protobuf.ProtobufMessage.internal_static_protobuf_Message_descriptor;
      }

      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMapField(
          int number) {
        switch (number) {
          case 6:
            return internalGetParameters();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMutableMapField(
          int number) {
        switch (number) {
          case 6:
            return internalGetMutableParameters();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return xyz.shiqihao.misc.protobuf.ProtobufMessage.internal_static_protobuf_Message_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                xyz.shiqihao.misc.protobuf.ProtobufMessage.Message.class, xyz.shiqihao.misc.protobuf.ProtobufMessage.Message.Builder.class);
      }

      // Construct using xyz.shiqihao.misc.protobuf.ProtobufMessage.Message.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        id_ = "";

        signName_ = "";

        template_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000004);
        receiver_ = "";

        areaCode_ = "";

        internalGetMutableParameters().clear();
        created_ = 0L;

        expires_ = 0;

        smsProvider_ = 0;

        providerKey_ = "";

        providerValue_ = "";

        sendPath_ = "";

        templateParam_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return xyz.shiqihao.misc.protobuf.ProtobufMessage.internal_static_protobuf_Message_descriptor;
      }

      @java.lang.Override
      public xyz.shiqihao.misc.protobuf.ProtobufMessage.Message getDefaultInstanceForType() {
        return xyz.shiqihao.misc.protobuf.ProtobufMessage.Message.getDefaultInstance();
      }

      @java.lang.Override
      public xyz.shiqihao.misc.protobuf.ProtobufMessage.Message build() {
        xyz.shiqihao.misc.protobuf.ProtobufMessage.Message result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public xyz.shiqihao.misc.protobuf.ProtobufMessage.Message buildPartial() {
        xyz.shiqihao.misc.protobuf.ProtobufMessage.Message result = new xyz.shiqihao.misc.protobuf.ProtobufMessage.Message(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.id_ = id_;
        result.signName_ = signName_;
        if (((bitField0_ & 0x00000004) != 0)) {
          template_ = template_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000004);
        }
        result.template_ = template_;
        result.receiver_ = receiver_;
        result.areaCode_ = areaCode_;
        result.parameters_ = internalGetParameters();
        result.parameters_.makeImmutable();
        result.created_ = created_;
        result.expires_ = expires_;
        result.smsProvider_ = smsProvider_;
        result.providerKey_ = providerKey_;
        result.providerValue_ = providerValue_;
        result.sendPath_ = sendPath_;
        result.templateParam_ = templateParam_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof xyz.shiqihao.misc.protobuf.ProtobufMessage.Message) {
          return mergeFrom((xyz.shiqihao.misc.protobuf.ProtobufMessage.Message)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(xyz.shiqihao.misc.protobuf.ProtobufMessage.Message other) {
        if (other == xyz.shiqihao.misc.protobuf.ProtobufMessage.Message.getDefaultInstance()) return this;
        if (!other.getId().isEmpty()) {
          id_ = other.id_;
          onChanged();
        }
        if (!other.getSignName().isEmpty()) {
          signName_ = other.signName_;
          onChanged();
        }
        if (!other.template_.isEmpty()) {
          if (template_.isEmpty()) {
            template_ = other.template_;
            bitField0_ = (bitField0_ & ~0x00000004);
          } else {
            ensureTemplateIsMutable();
            template_.addAll(other.template_);
          }
          onChanged();
        }
        if (!other.getReceiver().isEmpty()) {
          receiver_ = other.receiver_;
          onChanged();
        }
        if (!other.getAreaCode().isEmpty()) {
          areaCode_ = other.areaCode_;
          onChanged();
        }
        internalGetMutableParameters().mergeFrom(
            other.internalGetParameters());
        if (other.getCreated() != 0L) {
          setCreated(other.getCreated());
        }
        if (other.getExpires() != 0) {
          setExpires(other.getExpires());
        }
        if (other.smsProvider_ != 0) {
          setSmsProviderValue(other.getSmsProviderValue());
        }
        if (!other.getProviderKey().isEmpty()) {
          providerKey_ = other.providerKey_;
          onChanged();
        }
        if (!other.getProviderValue().isEmpty()) {
          providerValue_ = other.providerValue_;
          onChanged();
        }
        if (!other.getSendPath().isEmpty()) {
          sendPath_ = other.sendPath_;
          onChanged();
        }
        if (!other.getTemplateParam().isEmpty()) {
          templateParam_ = other.templateParam_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        xyz.shiqihao.misc.protobuf.ProtobufMessage.Message parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (xyz.shiqihao.misc.protobuf.ProtobufMessage.Message) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object id_ = "";
      /**
       * <code>string id = 1;</code>
       */
      public java.lang.String getId() {
        java.lang.Object ref = id_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          id_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string id = 1;</code>
       */
      public com.google.protobuf.ByteString
          getIdBytes() {
        java.lang.Object ref = id_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          id_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string id = 1;</code>
       */
      public Builder setId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string id = 1;</code>
       */
      public Builder clearId() {
        
        id_ = getDefaultInstance().getId();
        onChanged();
        return this;
      }
      /**
       * <code>string id = 1;</code>
       */
      public Builder setIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        id_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object signName_ = "";
      /**
       * <code>string sign_name = 2;</code>
       */
      public java.lang.String getSignName() {
        java.lang.Object ref = signName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          signName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string sign_name = 2;</code>
       */
      public com.google.protobuf.ByteString
          getSignNameBytes() {
        java.lang.Object ref = signName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          signName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string sign_name = 2;</code>
       */
      public Builder setSignName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        signName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string sign_name = 2;</code>
       */
      public Builder clearSignName() {
        
        signName_ = getDefaultInstance().getSignName();
        onChanged();
        return this;
      }
      /**
       * <code>string sign_name = 2;</code>
       */
      public Builder setSignNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        signName_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.LazyStringList template_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureTemplateIsMutable() {
        if (!((bitField0_ & 0x00000004) != 0)) {
          template_ = new com.google.protobuf.LazyStringArrayList(template_);
          bitField0_ |= 0x00000004;
         }
      }
      /**
       * <code>repeated string template = 3;</code>
       */
      public com.google.protobuf.ProtocolStringList
          getTemplateList() {
        return template_.getUnmodifiableView();
      }
      /**
       * <code>repeated string template = 3;</code>
       */
      public int getTemplateCount() {
        return template_.size();
      }
      /**
       * <code>repeated string template = 3;</code>
       */
      public java.lang.String getTemplate(int index) {
        return template_.get(index);
      }
      /**
       * <code>repeated string template = 3;</code>
       */
      public com.google.protobuf.ByteString
          getTemplateBytes(int index) {
        return template_.getByteString(index);
      }
      /**
       * <code>repeated string template = 3;</code>
       */
      public Builder setTemplate(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureTemplateIsMutable();
        template_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string template = 3;</code>
       */
      public Builder addTemplate(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureTemplateIsMutable();
        template_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string template = 3;</code>
       */
      public Builder addAllTemplate(
          java.lang.Iterable<java.lang.String> values) {
        ensureTemplateIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, template_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string template = 3;</code>
       */
      public Builder clearTemplate() {
        template_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string template = 3;</code>
       */
      public Builder addTemplateBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        ensureTemplateIsMutable();
        template_.add(value);
        onChanged();
        return this;
      }

      private java.lang.Object receiver_ = "";
      /**
       * <code>string receiver = 4;</code>
       */
      public java.lang.String getReceiver() {
        java.lang.Object ref = receiver_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          receiver_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string receiver = 4;</code>
       */
      public com.google.protobuf.ByteString
          getReceiverBytes() {
        java.lang.Object ref = receiver_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          receiver_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string receiver = 4;</code>
       */
      public Builder setReceiver(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        receiver_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string receiver = 4;</code>
       */
      public Builder clearReceiver() {
        
        receiver_ = getDefaultInstance().getReceiver();
        onChanged();
        return this;
      }
      /**
       * <code>string receiver = 4;</code>
       */
      public Builder setReceiverBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        receiver_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object areaCode_ = "";
      /**
       * <code>string areaCode = 5;</code>
       */
      public java.lang.String getAreaCode() {
        java.lang.Object ref = areaCode_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          areaCode_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string areaCode = 5;</code>
       */
      public com.google.protobuf.ByteString
          getAreaCodeBytes() {
        java.lang.Object ref = areaCode_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          areaCode_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string areaCode = 5;</code>
       */
      public Builder setAreaCode(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        areaCode_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string areaCode = 5;</code>
       */
      public Builder clearAreaCode() {
        
        areaCode_ = getDefaultInstance().getAreaCode();
        onChanged();
        return this;
      }
      /**
       * <code>string areaCode = 5;</code>
       */
      public Builder setAreaCodeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        areaCode_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.MapField<
          java.lang.String, java.lang.String> parameters_;
      private com.google.protobuf.MapField<java.lang.String, java.lang.String>
      internalGetParameters() {
        if (parameters_ == null) {
          return com.google.protobuf.MapField.emptyMapField(
              ParametersDefaultEntryHolder.defaultEntry);
        }
        return parameters_;
      }
      private com.google.protobuf.MapField<java.lang.String, java.lang.String>
      internalGetMutableParameters() {
        onChanged();;
        if (parameters_ == null) {
          parameters_ = com.google.protobuf.MapField.newMapField(
              ParametersDefaultEntryHolder.defaultEntry);
        }
        if (!parameters_.isMutable()) {
          parameters_ = parameters_.copy();
        }
        return parameters_;
      }

      public int getParametersCount() {
        return internalGetParameters().getMap().size();
      }
      /**
       * <code>map&lt;string, string&gt; parameters = 6;</code>
       */

      public boolean containsParameters(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        return internalGetParameters().getMap().containsKey(key);
      }
      /**
       * Use {@link #getParametersMap()} instead.
       */
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, java.lang.String> getParameters() {
        return getParametersMap();
      }
      /**
       * <code>map&lt;string, string&gt; parameters = 6;</code>
       */

      public java.util.Map<java.lang.String, java.lang.String> getParametersMap() {
        return internalGetParameters().getMap();
      }
      /**
       * <code>map&lt;string, string&gt; parameters = 6;</code>
       */

      public java.lang.String getParametersOrDefault(
          java.lang.String key,
          java.lang.String defaultValue) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        java.util.Map<java.lang.String, java.lang.String> map =
            internalGetParameters().getMap();
        return map.containsKey(key) ? map.get(key) : defaultValue;
      }
      /**
       * <code>map&lt;string, string&gt; parameters = 6;</code>
       */

      public java.lang.String getParametersOrThrow(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        java.util.Map<java.lang.String, java.lang.String> map =
            internalGetParameters().getMap();
        if (!map.containsKey(key)) {
          throw new java.lang.IllegalArgumentException();
        }
        return map.get(key);
      }

      public Builder clearParameters() {
        internalGetMutableParameters().getMutableMap()
            .clear();
        return this;
      }
      /**
       * <code>map&lt;string, string&gt; parameters = 6;</code>
       */

      public Builder removeParameters(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        internalGetMutableParameters().getMutableMap()
            .remove(key);
        return this;
      }
      /**
       * Use alternate mutation accessors instead.
       */
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, java.lang.String>
      getMutableParameters() {
        return internalGetMutableParameters().getMutableMap();
      }
      /**
       * <code>map&lt;string, string&gt; parameters = 6;</code>
       */
      public Builder putParameters(
          java.lang.String key,
          java.lang.String value) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        if (value == null) { throw new java.lang.NullPointerException(); }
        internalGetMutableParameters().getMutableMap()
            .put(key, value);
        return this;
      }
      /**
       * <code>map&lt;string, string&gt; parameters = 6;</code>
       */

      public Builder putAllParameters(
          java.util.Map<java.lang.String, java.lang.String> values) {
        internalGetMutableParameters().getMutableMap()
            .putAll(values);
        return this;
      }

      private long created_ ;
      /**
       * <code>int64 created = 7;</code>
       */
      public long getCreated() {
        return created_;
      }
      /**
       * <code>int64 created = 7;</code>
       */
      public Builder setCreated(long value) {
        
        created_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 created = 7;</code>
       */
      public Builder clearCreated() {
        
        created_ = 0L;
        onChanged();
        return this;
      }

      private int expires_ ;
      /**
       * <code>int32 expires = 8;</code>
       */
      public int getExpires() {
        return expires_;
      }
      /**
       * <code>int32 expires = 8;</code>
       */
      public Builder setExpires(int value) {
        
        expires_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 expires = 8;</code>
       */
      public Builder clearExpires() {
        
        expires_ = 0;
        onChanged();
        return this;
      }

      private int smsProvider_ = 0;
      /**
       * <code>.protobuf.Message.SmsProvider sms_provider = 9;</code>
       */
      public int getSmsProviderValue() {
        return smsProvider_;
      }
      /**
       * <code>.protobuf.Message.SmsProvider sms_provider = 9;</code>
       */
      public Builder setSmsProviderValue(int value) {
        smsProvider_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.protobuf.Message.SmsProvider sms_provider = 9;</code>
       */
      public xyz.shiqihao.misc.protobuf.ProtobufMessage.Message.SmsProvider getSmsProvider() {
        @SuppressWarnings("deprecation")
        xyz.shiqihao.misc.protobuf.ProtobufMessage.Message.SmsProvider result = xyz.shiqihao.misc.protobuf.ProtobufMessage.Message.SmsProvider.valueOf(smsProvider_);
        return result == null ? xyz.shiqihao.misc.protobuf.ProtobufMessage.Message.SmsProvider.UNRECOGNIZED : result;
      }
      /**
       * <code>.protobuf.Message.SmsProvider sms_provider = 9;</code>
       */
      public Builder setSmsProvider(xyz.shiqihao.misc.protobuf.ProtobufMessage.Message.SmsProvider value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        smsProvider_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.protobuf.Message.SmsProvider sms_provider = 9;</code>
       */
      public Builder clearSmsProvider() {
        
        smsProvider_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object providerKey_ = "";
      /**
       * <code>string provider_key = 10;</code>
       */
      public java.lang.String getProviderKey() {
        java.lang.Object ref = providerKey_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          providerKey_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string provider_key = 10;</code>
       */
      public com.google.protobuf.ByteString
          getProviderKeyBytes() {
        java.lang.Object ref = providerKey_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          providerKey_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string provider_key = 10;</code>
       */
      public Builder setProviderKey(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        providerKey_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string provider_key = 10;</code>
       */
      public Builder clearProviderKey() {
        
        providerKey_ = getDefaultInstance().getProviderKey();
        onChanged();
        return this;
      }
      /**
       * <code>string provider_key = 10;</code>
       */
      public Builder setProviderKeyBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        providerKey_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object providerValue_ = "";
      /**
       * <code>string provider_value = 12;</code>
       */
      public java.lang.String getProviderValue() {
        java.lang.Object ref = providerValue_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          providerValue_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string provider_value = 12;</code>
       */
      public com.google.protobuf.ByteString
          getProviderValueBytes() {
        java.lang.Object ref = providerValue_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          providerValue_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string provider_value = 12;</code>
       */
      public Builder setProviderValue(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        providerValue_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string provider_value = 12;</code>
       */
      public Builder clearProviderValue() {
        
        providerValue_ = getDefaultInstance().getProviderValue();
        onChanged();
        return this;
      }
      /**
       * <code>string provider_value = 12;</code>
       */
      public Builder setProviderValueBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        providerValue_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object sendPath_ = "";
      /**
       * <pre>
       * 请求供应商的地址,部分厂商需要设置.
       * </pre>
       *
       * <code>string send_path = 13;</code>
       */
      public java.lang.String getSendPath() {
        java.lang.Object ref = sendPath_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          sendPath_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * 请求供应商的地址,部分厂商需要设置.
       * </pre>
       *
       * <code>string send_path = 13;</code>
       */
      public com.google.protobuf.ByteString
          getSendPathBytes() {
        java.lang.Object ref = sendPath_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          sendPath_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 请求供应商的地址,部分厂商需要设置.
       * </pre>
       *
       * <code>string send_path = 13;</code>
       */
      public Builder setSendPath(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        sendPath_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 请求供应商的地址,部分厂商需要设置.
       * </pre>
       *
       * <code>string send_path = 13;</code>
       */
      public Builder clearSendPath() {
        
        sendPath_ = getDefaultInstance().getSendPath();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 请求供应商的地址,部分厂商需要设置.
       * </pre>
       *
       * <code>string send_path = 13;</code>
       */
      public Builder setSendPathBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        sendPath_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object templateParam_ = "";
      /**
       * <pre>
       * 短信模板中的变量,部分厂商需要
       * </pre>
       *
       * <code>string template_param = 14;</code>
       */
      public java.lang.String getTemplateParam() {
        java.lang.Object ref = templateParam_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          templateParam_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * 短信模板中的变量,部分厂商需要
       * </pre>
       *
       * <code>string template_param = 14;</code>
       */
      public com.google.protobuf.ByteString
          getTemplateParamBytes() {
        java.lang.Object ref = templateParam_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          templateParam_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 短信模板中的变量,部分厂商需要
       * </pre>
       *
       * <code>string template_param = 14;</code>
       */
      public Builder setTemplateParam(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        templateParam_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 短信模板中的变量,部分厂商需要
       * </pre>
       *
       * <code>string template_param = 14;</code>
       */
      public Builder clearTemplateParam() {
        
        templateParam_ = getDefaultInstance().getTemplateParam();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 短信模板中的变量,部分厂商需要
       * </pre>
       *
       * <code>string template_param = 14;</code>
       */
      public Builder setTemplateParamBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        templateParam_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:protobuf.Message)
    }

    // @@protoc_insertion_point(class_scope:protobuf.Message)
    private static final xyz.shiqihao.misc.protobuf.ProtobufMessage.Message DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new xyz.shiqihao.misc.protobuf.ProtobufMessage.Message();
    }

    public static xyz.shiqihao.misc.protobuf.ProtobufMessage.Message getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Message>
        PARSER = new com.google.protobuf.AbstractParser<Message>() {
      @java.lang.Override
      public Message parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Message(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Message> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Message> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public xyz.shiqihao.misc.protobuf.ProtobufMessage.Message getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protobuf_Message_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protobuf_Message_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protobuf_Message_ParametersEntry_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protobuf_Message_ParametersEntry_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\037src/main/protobuf/message.proto\022\010proto" +
      "buf\"\257\003\n\007Message\022\n\n\002id\030\001 \001(\t\022\021\n\tsign_name" +
      "\030\002 \001(\t\022\020\n\010template\030\003 \003(\t\022\020\n\010receiver\030\004 \001" +
      "(\t\022\020\n\010areaCode\030\005 \001(\t\0225\n\nparameters\030\006 \003(\013" +
      "2!.protobuf.Message.ParametersEntry\022\017\n\007c" +
      "reated\030\007 \001(\003\022\017\n\007expires\030\010 \001(\005\0223\n\014sms_pro" +
      "vider\030\t \001(\0162\035.protobuf.Message.SmsProvid" +
      "er\022\024\n\014provider_key\030\n \001(\t\022\026\n\016provider_val" +
      "ue\030\014 \001(\t\022\021\n\tsend_path\030\r \001(\t\022\026\n\016template_" +
      "param\030\016 \001(\t\0321\n\017ParametersEntry\022\013\n\003key\030\001 " +
      "\001(\t\022\r\n\005value\030\002 \001(\t:\0028\001\"5\n\013SmsProvider\022\n\n" +
      "\006ALIYUN\020\000\022\013\n\007YUNPIAN\020\001\022\r\n\tCHUANGLAN\020\002B-\n" +
      "\032xyz.shiqihao.misc.protobufB\017ProtobufMes" +
      "sageb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_protobuf_Message_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_protobuf_Message_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protobuf_Message_descriptor,
        new java.lang.String[] { "Id", "SignName", "Template", "Receiver", "AreaCode", "Parameters", "Created", "Expires", "SmsProvider", "ProviderKey", "ProviderValue", "SendPath", "TemplateParam", });
    internal_static_protobuf_Message_ParametersEntry_descriptor =
      internal_static_protobuf_Message_descriptor.getNestedTypes().get(0);
    internal_static_protobuf_Message_ParametersEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protobuf_Message_ParametersEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
