// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/protobuf/message.proto

package xyz.shiqihao.proto;

public final class ProtobufMessage {
  private ProtobufMessage() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface MessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:protobuf.Message)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .protobuf.Message.UserInfo user_info = 1;</code>
     */
    java.util.List<xyz.shiqihao.proto.ProtobufMessage.Message.UserInfo> 
        getUserInfoList();
    /**
     * <code>repeated .protobuf.Message.UserInfo user_info = 1;</code>
     */
    xyz.shiqihao.proto.ProtobufMessage.Message.UserInfo getUserInfo(int index);
    /**
     * <code>repeated .protobuf.Message.UserInfo user_info = 1;</code>
     */
    int getUserInfoCount();
    /**
     * <code>repeated .protobuf.Message.UserInfo user_info = 1;</code>
     */
    java.util.List<? extends xyz.shiqihao.proto.ProtobufMessage.Message.UserInfoOrBuilder> 
        getUserInfoOrBuilderList();
    /**
     * <code>repeated .protobuf.Message.UserInfo user_info = 1;</code>
     */
    xyz.shiqihao.proto.ProtobufMessage.Message.UserInfoOrBuilder getUserInfoOrBuilder(
        int index);

    /**
     * <code>.protobuf.Message.SmsProvider sms_provider = 2;</code>
     */
    int getSmsProviderValue();
    /**
     * <code>.protobuf.Message.SmsProvider sms_provider = 2;</code>
     */
    xyz.shiqihao.proto.ProtobufMessage.Message.SmsProvider getSmsProvider();

    /**
     * <code>string provider_key = 3;</code>
     */
    java.lang.String getProviderKey();
    /**
     * <code>string provider_key = 3;</code>
     */
    com.google.protobuf.ByteString
        getProviderKeyBytes();

    /**
     * <code>string provider_value = 4;</code>
     */
    java.lang.String getProviderValue();
    /**
     * <code>string provider_value = 4;</code>
     */
    com.google.protobuf.ByteString
        getProviderValueBytes();

    /**
     * <code>string sign_name = 5;</code>
     */
    java.lang.String getSignName();
    /**
     * <code>string sign_name = 5;</code>
     */
    com.google.protobuf.ByteString
        getSignNameBytes();

    /**
     * <code>string template_code = 6;</code>
     */
    java.lang.String getTemplateCode();
    /**
     * <code>string template_code = 6;</code>
     */
    com.google.protobuf.ByteString
        getTemplateCodeBytes();

    /**
     * <code>string template_content = 7;</code>
     */
    java.lang.String getTemplateContent();
    /**
     * <code>string template_content = 7;</code>
     */
    com.google.protobuf.ByteString
        getTemplateContentBytes();
  }
  /**
   * Protobuf type {@code protobuf.Message}
   */
  public  static final class Message extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:protobuf.Message)
      MessageOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Message.newBuilder() to construct.
    private Message(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Message() {
      userInfo_ = java.util.Collections.emptyList();
      smsProvider_ = 0;
      providerKey_ = "";
      providerValue_ = "";
      signName_ = "";
      templateCode_ = "";
      templateContent_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Message(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                userInfo_ = new java.util.ArrayList<xyz.shiqihao.proto.ProtobufMessage.Message.UserInfo>();
                mutable_bitField0_ |= 0x00000001;
              }
              userInfo_.add(
                  input.readMessage(xyz.shiqihao.proto.ProtobufMessage.Message.UserInfo.parser(), extensionRegistry));
              break;
            }
            case 16: {
              int rawValue = input.readEnum();

              smsProvider_ = rawValue;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              providerKey_ = s;
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              providerValue_ = s;
              break;
            }
            case 42: {
              java.lang.String s = input.readStringRequireUtf8();

              signName_ = s;
              break;
            }
            case 50: {
              java.lang.String s = input.readStringRequireUtf8();

              templateCode_ = s;
              break;
            }
            case 58: {
              java.lang.String s = input.readStringRequireUtf8();

              templateContent_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          userInfo_ = java.util.Collections.unmodifiableList(userInfo_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return xyz.shiqihao.proto.ProtobufMessage.internal_static_protobuf_Message_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return xyz.shiqihao.proto.ProtobufMessage.internal_static_protobuf_Message_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              xyz.shiqihao.proto.ProtobufMessage.Message.class, xyz.shiqihao.proto.ProtobufMessage.Message.Builder.class);
    }

    /**
     * Protobuf enum {@code protobuf.Message.SmsProvider}
     */
    public enum SmsProvider
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>ALIYUN = 0;</code>
       */
      ALIYUN(0),
      /**
       * <code>YUNPIAN = 1;</code>
       */
      YUNPIAN(1),
      UNRECOGNIZED(-1),
      ;

      /**
       * <code>ALIYUN = 0;</code>
       */
      public static final int ALIYUN_VALUE = 0;
      /**
       * <code>YUNPIAN = 1;</code>
       */
      public static final int YUNPIAN_VALUE = 1;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static SmsProvider valueOf(int value) {
        return forNumber(value);
      }

      public static SmsProvider forNumber(int value) {
        switch (value) {
          case 0: return ALIYUN;
          case 1: return YUNPIAN;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<SmsProvider>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          SmsProvider> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<SmsProvider>() {
              public SmsProvider findValueByNumber(int number) {
                return SmsProvider.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return xyz.shiqihao.proto.ProtobufMessage.Message.getDescriptor().getEnumTypes().get(0);
      }

      private static final SmsProvider[] VALUES = values();

      public static SmsProvider valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private SmsProvider(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:protobuf.Message.SmsProvider)
    }

    public interface UserInfoOrBuilder extends
        // @@protoc_insertion_point(interface_extends:protobuf.Message.UserInfo)
        com.google.protobuf.MessageOrBuilder {

      /**
       * <code>repeated string value = 1;</code>
       */
      java.util.List<java.lang.String>
          getValueList();
      /**
       * <code>repeated string value = 1;</code>
       */
      int getValueCount();
      /**
       * <code>repeated string value = 1;</code>
       */
      java.lang.String getValue(int index);
      /**
       * <code>repeated string value = 1;</code>
       */
      com.google.protobuf.ByteString
          getValueBytes(int index);
    }
    /**
     * Protobuf type {@code protobuf.Message.UserInfo}
     */
    public  static final class UserInfo extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:protobuf.Message.UserInfo)
        UserInfoOrBuilder {
    private static final long serialVersionUID = 0L;
      // Use UserInfo.newBuilder() to construct.
      private UserInfo(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
      }
      private UserInfo() {
        value_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      }

      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
        return this.unknownFields;
      }
      private UserInfo(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        this();
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                java.lang.String s = input.readStringRequireUtf8();
                if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                  value_ = new com.google.protobuf.LazyStringArrayList();
                  mutable_bitField0_ |= 0x00000001;
                }
                value_.add(s);
                break;
              }
              default: {
                if (!parseUnknownField(
                    input, unknownFields, extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e).setUnfinishedMessage(this);
        } finally {
          if (((mutable_bitField0_ & 0x00000001) != 0)) {
            value_ = value_.getUnmodifiableView();
          }
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return xyz.shiqihao.proto.ProtobufMessage.internal_static_protobuf_Message_UserInfo_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return xyz.shiqihao.proto.ProtobufMessage.internal_static_protobuf_Message_UserInfo_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                xyz.shiqihao.proto.ProtobufMessage.Message.UserInfo.class, xyz.shiqihao.proto.ProtobufMessage.Message.UserInfo.Builder.class);
      }

      public static final int VALUE_FIELD_NUMBER = 1;
      private com.google.protobuf.LazyStringList value_;
      /**
       * <code>repeated string value = 1;</code>
       */
      public com.google.protobuf.ProtocolStringList
          getValueList() {
        return value_;
      }
      /**
       * <code>repeated string value = 1;</code>
       */
      public int getValueCount() {
        return value_.size();
      }
      /**
       * <code>repeated string value = 1;</code>
       */
      public java.lang.String getValue(int index) {
        return value_.get(index);
      }
      /**
       * <code>repeated string value = 1;</code>
       */
      public com.google.protobuf.ByteString
          getValueBytes(int index) {
        return value_.getByteString(index);
      }

      private byte memoizedIsInitialized = -1;
      @java.lang.Override
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
      }

      @java.lang.Override
      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        for (int i = 0; i < value_.size(); i++) {
          com.google.protobuf.GeneratedMessageV3.writeString(output, 1, value_.getRaw(i));
        }
        unknownFields.writeTo(output);
      }

      @java.lang.Override
      public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        {
          int dataSize = 0;
          for (int i = 0; i < value_.size(); i++) {
            dataSize += computeStringSizeNoTag(value_.getRaw(i));
          }
          size += dataSize;
          size += 1 * getValueList().size();
        }
        size += unknownFields.getSerializedSize();
        memoizedSize = size;
        return size;
      }

      @java.lang.Override
      public boolean equals(final java.lang.Object obj) {
        if (obj == this) {
         return true;
        }
        if (!(obj instanceof xyz.shiqihao.proto.ProtobufMessage.Message.UserInfo)) {
          return super.equals(obj);
        }
        xyz.shiqihao.proto.ProtobufMessage.Message.UserInfo other = (xyz.shiqihao.proto.ProtobufMessage.Message.UserInfo) obj;

        if (!getValueList()
            .equals(other.getValueList())) return false;
        if (!unknownFields.equals(other.unknownFields)) return false;
        return true;
      }

      @java.lang.Override
      public int hashCode() {
        if (memoizedHashCode != 0) {
          return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        if (getValueCount() > 0) {
          hash = (37 * hash) + VALUE_FIELD_NUMBER;
          hash = (53 * hash) + getValueList().hashCode();
        }
        hash = (29 * hash) + unknownFields.hashCode();
        memoizedHashCode = hash;
        return hash;
      }

      public static xyz.shiqihao.proto.ProtobufMessage.Message.UserInfo parseFrom(
          java.nio.ByteBuffer data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static xyz.shiqihao.proto.ProtobufMessage.Message.UserInfo parseFrom(
          java.nio.ByteBuffer data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static xyz.shiqihao.proto.ProtobufMessage.Message.UserInfo parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static xyz.shiqihao.proto.ProtobufMessage.Message.UserInfo parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static xyz.shiqihao.proto.ProtobufMessage.Message.UserInfo parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static xyz.shiqihao.proto.ProtobufMessage.Message.UserInfo parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static xyz.shiqihao.proto.ProtobufMessage.Message.UserInfo parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static xyz.shiqihao.proto.ProtobufMessage.Message.UserInfo parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }
      public static xyz.shiqihao.proto.ProtobufMessage.Message.UserInfo parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input);
      }
      public static xyz.shiqihao.proto.ProtobufMessage.Message.UserInfo parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
      }
      public static xyz.shiqihao.proto.ProtobufMessage.Message.UserInfo parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static xyz.shiqihao.proto.ProtobufMessage.Message.UserInfo parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }

      @java.lang.Override
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
      }
      public static Builder newBuilder(xyz.shiqihao.proto.ProtobufMessage.Message.UserInfo prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
      }
      @java.lang.Override
      public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
            ? new Builder() : new Builder().mergeFrom(this);
      }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code protobuf.Message.UserInfo}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:protobuf.Message.UserInfo)
          xyz.shiqihao.proto.ProtobufMessage.Message.UserInfoOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return xyz.shiqihao.proto.ProtobufMessage.internal_static_protobuf_Message_UserInfo_descriptor;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return xyz.shiqihao.proto.ProtobufMessage.internal_static_protobuf_Message_UserInfo_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  xyz.shiqihao.proto.ProtobufMessage.Message.UserInfo.class, xyz.shiqihao.proto.ProtobufMessage.Message.UserInfo.Builder.class);
        }

        // Construct using xyz.shiqihao.proto.ProtobufMessage.Message.UserInfo.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessageV3
                  .alwaysUseFieldBuilders) {
          }
        }
        @java.lang.Override
        public Builder clear() {
          super.clear();
          value_ = com.google.protobuf.LazyStringArrayList.EMPTY;
          bitField0_ = (bitField0_ & ~0x00000001);
          return this;
        }

        @java.lang.Override
        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return xyz.shiqihao.proto.ProtobufMessage.internal_static_protobuf_Message_UserInfo_descriptor;
        }

        @java.lang.Override
        public xyz.shiqihao.proto.ProtobufMessage.Message.UserInfo getDefaultInstanceForType() {
          return xyz.shiqihao.proto.ProtobufMessage.Message.UserInfo.getDefaultInstance();
        }

        @java.lang.Override
        public xyz.shiqihao.proto.ProtobufMessage.Message.UserInfo build() {
          xyz.shiqihao.proto.ProtobufMessage.Message.UserInfo result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        @java.lang.Override
        public xyz.shiqihao.proto.ProtobufMessage.Message.UserInfo buildPartial() {
          xyz.shiqihao.proto.ProtobufMessage.Message.UserInfo result = new xyz.shiqihao.proto.ProtobufMessage.Message.UserInfo(this);
          int from_bitField0_ = bitField0_;
          if (((bitField0_ & 0x00000001) != 0)) {
            value_ = value_.getUnmodifiableView();
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.value_ = value_;
          onBuilt();
          return result;
        }

        @java.lang.Override
        public Builder clone() {
          return super.clone();
        }
        @java.lang.Override
        public Builder setField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
          return super.setField(field, value);
        }
        @java.lang.Override
        public Builder clearField(
            com.google.protobuf.Descriptors.FieldDescriptor field) {
          return super.clearField(field);
        }
        @java.lang.Override
        public Builder clearOneof(
            com.google.protobuf.Descriptors.OneofDescriptor oneof) {
          return super.clearOneof(oneof);
        }
        @java.lang.Override
        public Builder setRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            int index, java.lang.Object value) {
          return super.setRepeatedField(field, index, value);
        }
        @java.lang.Override
        public Builder addRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
          return super.addRepeatedField(field, value);
        }
        @java.lang.Override
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof xyz.shiqihao.proto.ProtobufMessage.Message.UserInfo) {
            return mergeFrom((xyz.shiqihao.proto.ProtobufMessage.Message.UserInfo)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(xyz.shiqihao.proto.ProtobufMessage.Message.UserInfo other) {
          if (other == xyz.shiqihao.proto.ProtobufMessage.Message.UserInfo.getDefaultInstance()) return this;
          if (!other.value_.isEmpty()) {
            if (value_.isEmpty()) {
              value_ = other.value_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureValueIsMutable();
              value_.addAll(other.value_);
            }
            onChanged();
          }
          this.mergeUnknownFields(other.unknownFields);
          onChanged();
          return this;
        }

        @java.lang.Override
        public final boolean isInitialized() {
          return true;
        }

        @java.lang.Override
        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          xyz.shiqihao.proto.ProtobufMessage.Message.UserInfo parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (xyz.shiqihao.proto.ProtobufMessage.Message.UserInfo) e.getUnfinishedMessage();
            throw e.unwrapIOException();
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }
        private int bitField0_;

        private com.google.protobuf.LazyStringList value_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        private void ensureValueIsMutable() {
          if (!((bitField0_ & 0x00000001) != 0)) {
            value_ = new com.google.protobuf.LazyStringArrayList(value_);
            bitField0_ |= 0x00000001;
           }
        }
        /**
         * <code>repeated string value = 1;</code>
         */
        public com.google.protobuf.ProtocolStringList
            getValueList() {
          return value_.getUnmodifiableView();
        }
        /**
         * <code>repeated string value = 1;</code>
         */
        public int getValueCount() {
          return value_.size();
        }
        /**
         * <code>repeated string value = 1;</code>
         */
        public java.lang.String getValue(int index) {
          return value_.get(index);
        }
        /**
         * <code>repeated string value = 1;</code>
         */
        public com.google.protobuf.ByteString
            getValueBytes(int index) {
          return value_.getByteString(index);
        }
        /**
         * <code>repeated string value = 1;</code>
         */
        public Builder setValue(
            int index, java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  ensureValueIsMutable();
          value_.set(index, value);
          onChanged();
          return this;
        }
        /**
         * <code>repeated string value = 1;</code>
         */
        public Builder addValue(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  ensureValueIsMutable();
          value_.add(value);
          onChanged();
          return this;
        }
        /**
         * <code>repeated string value = 1;</code>
         */
        public Builder addAllValue(
            java.lang.Iterable<java.lang.String> values) {
          ensureValueIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, value_);
          onChanged();
          return this;
        }
        /**
         * <code>repeated string value = 1;</code>
         */
        public Builder clearValue() {
          value_ = com.google.protobuf.LazyStringArrayList.EMPTY;
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
          return this;
        }
        /**
         * <code>repeated string value = 1;</code>
         */
        public Builder addValueBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
          ensureValueIsMutable();
          value_.add(value);
          onChanged();
          return this;
        }
        @java.lang.Override
        public final Builder setUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.setUnknownFields(unknownFields);
        }

        @java.lang.Override
        public final Builder mergeUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.mergeUnknownFields(unknownFields);
        }


        // @@protoc_insertion_point(builder_scope:protobuf.Message.UserInfo)
      }

      // @@protoc_insertion_point(class_scope:protobuf.Message.UserInfo)
      private static final xyz.shiqihao.proto.ProtobufMessage.Message.UserInfo DEFAULT_INSTANCE;
      static {
        DEFAULT_INSTANCE = new xyz.shiqihao.proto.ProtobufMessage.Message.UserInfo();
      }

      public static xyz.shiqihao.proto.ProtobufMessage.Message.UserInfo getDefaultInstance() {
        return DEFAULT_INSTANCE;
      }

      private static final com.google.protobuf.Parser<UserInfo>
          PARSER = new com.google.protobuf.AbstractParser<UserInfo>() {
        @java.lang.Override
        public UserInfo parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new UserInfo(input, extensionRegistry);
        }
      };

      public static com.google.protobuf.Parser<UserInfo> parser() {
        return PARSER;
      }

      @java.lang.Override
      public com.google.protobuf.Parser<UserInfo> getParserForType() {
        return PARSER;
      }

      @java.lang.Override
      public xyz.shiqihao.proto.ProtobufMessage.Message.UserInfo getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
      }

    }

    private int bitField0_;
    public static final int USER_INFO_FIELD_NUMBER = 1;
    private java.util.List<xyz.shiqihao.proto.ProtobufMessage.Message.UserInfo> userInfo_;
    /**
     * <code>repeated .protobuf.Message.UserInfo user_info = 1;</code>
     */
    public java.util.List<xyz.shiqihao.proto.ProtobufMessage.Message.UserInfo> getUserInfoList() {
      return userInfo_;
    }
    /**
     * <code>repeated .protobuf.Message.UserInfo user_info = 1;</code>
     */
    public java.util.List<? extends xyz.shiqihao.proto.ProtobufMessage.Message.UserInfoOrBuilder> 
        getUserInfoOrBuilderList() {
      return userInfo_;
    }
    /**
     * <code>repeated .protobuf.Message.UserInfo user_info = 1;</code>
     */
    public int getUserInfoCount() {
      return userInfo_.size();
    }
    /**
     * <code>repeated .protobuf.Message.UserInfo user_info = 1;</code>
     */
    public xyz.shiqihao.proto.ProtobufMessage.Message.UserInfo getUserInfo(int index) {
      return userInfo_.get(index);
    }
    /**
     * <code>repeated .protobuf.Message.UserInfo user_info = 1;</code>
     */
    public xyz.shiqihao.proto.ProtobufMessage.Message.UserInfoOrBuilder getUserInfoOrBuilder(
        int index) {
      return userInfo_.get(index);
    }

    public static final int SMS_PROVIDER_FIELD_NUMBER = 2;
    private int smsProvider_;
    /**
     * <code>.protobuf.Message.SmsProvider sms_provider = 2;</code>
     */
    public int getSmsProviderValue() {
      return smsProvider_;
    }
    /**
     * <code>.protobuf.Message.SmsProvider sms_provider = 2;</code>
     */
    public xyz.shiqihao.proto.ProtobufMessage.Message.SmsProvider getSmsProvider() {
      @SuppressWarnings("deprecation")
      xyz.shiqihao.proto.ProtobufMessage.Message.SmsProvider result = xyz.shiqihao.proto.ProtobufMessage.Message.SmsProvider.valueOf(smsProvider_);
      return result == null ? xyz.shiqihao.proto.ProtobufMessage.Message.SmsProvider.UNRECOGNIZED : result;
    }

    public static final int PROVIDER_KEY_FIELD_NUMBER = 3;
    private volatile java.lang.Object providerKey_;
    /**
     * <code>string provider_key = 3;</code>
     */
    public java.lang.String getProviderKey() {
      java.lang.Object ref = providerKey_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        providerKey_ = s;
        return s;
      }
    }
    /**
     * <code>string provider_key = 3;</code>
     */
    public com.google.protobuf.ByteString
        getProviderKeyBytes() {
      java.lang.Object ref = providerKey_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        providerKey_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PROVIDER_VALUE_FIELD_NUMBER = 4;
    private volatile java.lang.Object providerValue_;
    /**
     * <code>string provider_value = 4;</code>
     */
    public java.lang.String getProviderValue() {
      java.lang.Object ref = providerValue_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        providerValue_ = s;
        return s;
      }
    }
    /**
     * <code>string provider_value = 4;</code>
     */
    public com.google.protobuf.ByteString
        getProviderValueBytes() {
      java.lang.Object ref = providerValue_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        providerValue_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SIGN_NAME_FIELD_NUMBER = 5;
    private volatile java.lang.Object signName_;
    /**
     * <code>string sign_name = 5;</code>
     */
    public java.lang.String getSignName() {
      java.lang.Object ref = signName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        signName_ = s;
        return s;
      }
    }
    /**
     * <code>string sign_name = 5;</code>
     */
    public com.google.protobuf.ByteString
        getSignNameBytes() {
      java.lang.Object ref = signName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        signName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TEMPLATE_CODE_FIELD_NUMBER = 6;
    private volatile java.lang.Object templateCode_;
    /**
     * <code>string template_code = 6;</code>
     */
    public java.lang.String getTemplateCode() {
      java.lang.Object ref = templateCode_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        templateCode_ = s;
        return s;
      }
    }
    /**
     * <code>string template_code = 6;</code>
     */
    public com.google.protobuf.ByteString
        getTemplateCodeBytes() {
      java.lang.Object ref = templateCode_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        templateCode_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TEMPLATE_CONTENT_FIELD_NUMBER = 7;
    private volatile java.lang.Object templateContent_;
    /**
     * <code>string template_content = 7;</code>
     */
    public java.lang.String getTemplateContent() {
      java.lang.Object ref = templateContent_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        templateContent_ = s;
        return s;
      }
    }
    /**
     * <code>string template_content = 7;</code>
     */
    public com.google.protobuf.ByteString
        getTemplateContentBytes() {
      java.lang.Object ref = templateContent_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        templateContent_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < userInfo_.size(); i++) {
        output.writeMessage(1, userInfo_.get(i));
      }
      if (smsProvider_ != xyz.shiqihao.proto.ProtobufMessage.Message.SmsProvider.ALIYUN.getNumber()) {
        output.writeEnum(2, smsProvider_);
      }
      if (!getProviderKeyBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, providerKey_);
      }
      if (!getProviderValueBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, providerValue_);
      }
      if (!getSignNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, signName_);
      }
      if (!getTemplateCodeBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 6, templateCode_);
      }
      if (!getTemplateContentBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 7, templateContent_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < userInfo_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, userInfo_.get(i));
      }
      if (smsProvider_ != xyz.shiqihao.proto.ProtobufMessage.Message.SmsProvider.ALIYUN.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, smsProvider_);
      }
      if (!getProviderKeyBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, providerKey_);
      }
      if (!getProviderValueBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, providerValue_);
      }
      if (!getSignNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, signName_);
      }
      if (!getTemplateCodeBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, templateCode_);
      }
      if (!getTemplateContentBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, templateContent_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof xyz.shiqihao.proto.ProtobufMessage.Message)) {
        return super.equals(obj);
      }
      xyz.shiqihao.proto.ProtobufMessage.Message other = (xyz.shiqihao.proto.ProtobufMessage.Message) obj;

      if (!getUserInfoList()
          .equals(other.getUserInfoList())) return false;
      if (smsProvider_ != other.smsProvider_) return false;
      if (!getProviderKey()
          .equals(other.getProviderKey())) return false;
      if (!getProviderValue()
          .equals(other.getProviderValue())) return false;
      if (!getSignName()
          .equals(other.getSignName())) return false;
      if (!getTemplateCode()
          .equals(other.getTemplateCode())) return false;
      if (!getTemplateContent()
          .equals(other.getTemplateContent())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getUserInfoCount() > 0) {
        hash = (37 * hash) + USER_INFO_FIELD_NUMBER;
        hash = (53 * hash) + getUserInfoList().hashCode();
      }
      hash = (37 * hash) + SMS_PROVIDER_FIELD_NUMBER;
      hash = (53 * hash) + smsProvider_;
      hash = (37 * hash) + PROVIDER_KEY_FIELD_NUMBER;
      hash = (53 * hash) + getProviderKey().hashCode();
      hash = (37 * hash) + PROVIDER_VALUE_FIELD_NUMBER;
      hash = (53 * hash) + getProviderValue().hashCode();
      hash = (37 * hash) + SIGN_NAME_FIELD_NUMBER;
      hash = (53 * hash) + getSignName().hashCode();
      hash = (37 * hash) + TEMPLATE_CODE_FIELD_NUMBER;
      hash = (53 * hash) + getTemplateCode().hashCode();
      hash = (37 * hash) + TEMPLATE_CONTENT_FIELD_NUMBER;
      hash = (53 * hash) + getTemplateContent().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static xyz.shiqihao.proto.ProtobufMessage.Message parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static xyz.shiqihao.proto.ProtobufMessage.Message parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static xyz.shiqihao.proto.ProtobufMessage.Message parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static xyz.shiqihao.proto.ProtobufMessage.Message parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static xyz.shiqihao.proto.ProtobufMessage.Message parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static xyz.shiqihao.proto.ProtobufMessage.Message parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static xyz.shiqihao.proto.ProtobufMessage.Message parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static xyz.shiqihao.proto.ProtobufMessage.Message parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static xyz.shiqihao.proto.ProtobufMessage.Message parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static xyz.shiqihao.proto.ProtobufMessage.Message parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static xyz.shiqihao.proto.ProtobufMessage.Message parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static xyz.shiqihao.proto.ProtobufMessage.Message parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(xyz.shiqihao.proto.ProtobufMessage.Message prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code protobuf.Message}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:protobuf.Message)
        xyz.shiqihao.proto.ProtobufMessage.MessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return xyz.shiqihao.proto.ProtobufMessage.internal_static_protobuf_Message_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return xyz.shiqihao.proto.ProtobufMessage.internal_static_protobuf_Message_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                xyz.shiqihao.proto.ProtobufMessage.Message.class, xyz.shiqihao.proto.ProtobufMessage.Message.Builder.class);
      }

      // Construct using xyz.shiqihao.proto.ProtobufMessage.Message.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getUserInfoFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (userInfoBuilder_ == null) {
          userInfo_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          userInfoBuilder_.clear();
        }
        smsProvider_ = 0;

        providerKey_ = "";

        providerValue_ = "";

        signName_ = "";

        templateCode_ = "";

        templateContent_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return xyz.shiqihao.proto.ProtobufMessage.internal_static_protobuf_Message_descriptor;
      }

      @java.lang.Override
      public xyz.shiqihao.proto.ProtobufMessage.Message getDefaultInstanceForType() {
        return xyz.shiqihao.proto.ProtobufMessage.Message.getDefaultInstance();
      }

      @java.lang.Override
      public xyz.shiqihao.proto.ProtobufMessage.Message build() {
        xyz.shiqihao.proto.ProtobufMessage.Message result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public xyz.shiqihao.proto.ProtobufMessage.Message buildPartial() {
        xyz.shiqihao.proto.ProtobufMessage.Message result = new xyz.shiqihao.proto.ProtobufMessage.Message(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (userInfoBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            userInfo_ = java.util.Collections.unmodifiableList(userInfo_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.userInfo_ = userInfo_;
        } else {
          result.userInfo_ = userInfoBuilder_.build();
        }
        result.smsProvider_ = smsProvider_;
        result.providerKey_ = providerKey_;
        result.providerValue_ = providerValue_;
        result.signName_ = signName_;
        result.templateCode_ = templateCode_;
        result.templateContent_ = templateContent_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof xyz.shiqihao.proto.ProtobufMessage.Message) {
          return mergeFrom((xyz.shiqihao.proto.ProtobufMessage.Message)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(xyz.shiqihao.proto.ProtobufMessage.Message other) {
        if (other == xyz.shiqihao.proto.ProtobufMessage.Message.getDefaultInstance()) return this;
        if (userInfoBuilder_ == null) {
          if (!other.userInfo_.isEmpty()) {
            if (userInfo_.isEmpty()) {
              userInfo_ = other.userInfo_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureUserInfoIsMutable();
              userInfo_.addAll(other.userInfo_);
            }
            onChanged();
          }
        } else {
          if (!other.userInfo_.isEmpty()) {
            if (userInfoBuilder_.isEmpty()) {
              userInfoBuilder_.dispose();
              userInfoBuilder_ = null;
              userInfo_ = other.userInfo_;
              bitField0_ = (bitField0_ & ~0x00000001);
              userInfoBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getUserInfoFieldBuilder() : null;
            } else {
              userInfoBuilder_.addAllMessages(other.userInfo_);
            }
          }
        }
        if (other.smsProvider_ != 0) {
          setSmsProviderValue(other.getSmsProviderValue());
        }
        if (!other.getProviderKey().isEmpty()) {
          providerKey_ = other.providerKey_;
          onChanged();
        }
        if (!other.getProviderValue().isEmpty()) {
          providerValue_ = other.providerValue_;
          onChanged();
        }
        if (!other.getSignName().isEmpty()) {
          signName_ = other.signName_;
          onChanged();
        }
        if (!other.getTemplateCode().isEmpty()) {
          templateCode_ = other.templateCode_;
          onChanged();
        }
        if (!other.getTemplateContent().isEmpty()) {
          templateContent_ = other.templateContent_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        xyz.shiqihao.proto.ProtobufMessage.Message parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (xyz.shiqihao.proto.ProtobufMessage.Message) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<xyz.shiqihao.proto.ProtobufMessage.Message.UserInfo> userInfo_ =
        java.util.Collections.emptyList();
      private void ensureUserInfoIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          userInfo_ = new java.util.ArrayList<xyz.shiqihao.proto.ProtobufMessage.Message.UserInfo>(userInfo_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          xyz.shiqihao.proto.ProtobufMessage.Message.UserInfo, xyz.shiqihao.proto.ProtobufMessage.Message.UserInfo.Builder, xyz.shiqihao.proto.ProtobufMessage.Message.UserInfoOrBuilder> userInfoBuilder_;

      /**
       * <code>repeated .protobuf.Message.UserInfo user_info = 1;</code>
       */
      public java.util.List<xyz.shiqihao.proto.ProtobufMessage.Message.UserInfo> getUserInfoList() {
        if (userInfoBuilder_ == null) {
          return java.util.Collections.unmodifiableList(userInfo_);
        } else {
          return userInfoBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .protobuf.Message.UserInfo user_info = 1;</code>
       */
      public int getUserInfoCount() {
        if (userInfoBuilder_ == null) {
          return userInfo_.size();
        } else {
          return userInfoBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .protobuf.Message.UserInfo user_info = 1;</code>
       */
      public xyz.shiqihao.proto.ProtobufMessage.Message.UserInfo getUserInfo(int index) {
        if (userInfoBuilder_ == null) {
          return userInfo_.get(index);
        } else {
          return userInfoBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .protobuf.Message.UserInfo user_info = 1;</code>
       */
      public Builder setUserInfo(
          int index, xyz.shiqihao.proto.ProtobufMessage.Message.UserInfo value) {
        if (userInfoBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureUserInfoIsMutable();
          userInfo_.set(index, value);
          onChanged();
        } else {
          userInfoBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .protobuf.Message.UserInfo user_info = 1;</code>
       */
      public Builder setUserInfo(
          int index, xyz.shiqihao.proto.ProtobufMessage.Message.UserInfo.Builder builderForValue) {
        if (userInfoBuilder_ == null) {
          ensureUserInfoIsMutable();
          userInfo_.set(index, builderForValue.build());
          onChanged();
        } else {
          userInfoBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .protobuf.Message.UserInfo user_info = 1;</code>
       */
      public Builder addUserInfo(xyz.shiqihao.proto.ProtobufMessage.Message.UserInfo value) {
        if (userInfoBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureUserInfoIsMutable();
          userInfo_.add(value);
          onChanged();
        } else {
          userInfoBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .protobuf.Message.UserInfo user_info = 1;</code>
       */
      public Builder addUserInfo(
          int index, xyz.shiqihao.proto.ProtobufMessage.Message.UserInfo value) {
        if (userInfoBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureUserInfoIsMutable();
          userInfo_.add(index, value);
          onChanged();
        } else {
          userInfoBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .protobuf.Message.UserInfo user_info = 1;</code>
       */
      public Builder addUserInfo(
          xyz.shiqihao.proto.ProtobufMessage.Message.UserInfo.Builder builderForValue) {
        if (userInfoBuilder_ == null) {
          ensureUserInfoIsMutable();
          userInfo_.add(builderForValue.build());
          onChanged();
        } else {
          userInfoBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .protobuf.Message.UserInfo user_info = 1;</code>
       */
      public Builder addUserInfo(
          int index, xyz.shiqihao.proto.ProtobufMessage.Message.UserInfo.Builder builderForValue) {
        if (userInfoBuilder_ == null) {
          ensureUserInfoIsMutable();
          userInfo_.add(index, builderForValue.build());
          onChanged();
        } else {
          userInfoBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .protobuf.Message.UserInfo user_info = 1;</code>
       */
      public Builder addAllUserInfo(
          java.lang.Iterable<? extends xyz.shiqihao.proto.ProtobufMessage.Message.UserInfo> values) {
        if (userInfoBuilder_ == null) {
          ensureUserInfoIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, userInfo_);
          onChanged();
        } else {
          userInfoBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .protobuf.Message.UserInfo user_info = 1;</code>
       */
      public Builder clearUserInfo() {
        if (userInfoBuilder_ == null) {
          userInfo_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          userInfoBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .protobuf.Message.UserInfo user_info = 1;</code>
       */
      public Builder removeUserInfo(int index) {
        if (userInfoBuilder_ == null) {
          ensureUserInfoIsMutable();
          userInfo_.remove(index);
          onChanged();
        } else {
          userInfoBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .protobuf.Message.UserInfo user_info = 1;</code>
       */
      public xyz.shiqihao.proto.ProtobufMessage.Message.UserInfo.Builder getUserInfoBuilder(
          int index) {
        return getUserInfoFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .protobuf.Message.UserInfo user_info = 1;</code>
       */
      public xyz.shiqihao.proto.ProtobufMessage.Message.UserInfoOrBuilder getUserInfoOrBuilder(
          int index) {
        if (userInfoBuilder_ == null) {
          return userInfo_.get(index);  } else {
          return userInfoBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .protobuf.Message.UserInfo user_info = 1;</code>
       */
      public java.util.List<? extends xyz.shiqihao.proto.ProtobufMessage.Message.UserInfoOrBuilder> 
           getUserInfoOrBuilderList() {
        if (userInfoBuilder_ != null) {
          return userInfoBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(userInfo_);
        }
      }
      /**
       * <code>repeated .protobuf.Message.UserInfo user_info = 1;</code>
       */
      public xyz.shiqihao.proto.ProtobufMessage.Message.UserInfo.Builder addUserInfoBuilder() {
        return getUserInfoFieldBuilder().addBuilder(
            xyz.shiqihao.proto.ProtobufMessage.Message.UserInfo.getDefaultInstance());
      }
      /**
       * <code>repeated .protobuf.Message.UserInfo user_info = 1;</code>
       */
      public xyz.shiqihao.proto.ProtobufMessage.Message.UserInfo.Builder addUserInfoBuilder(
          int index) {
        return getUserInfoFieldBuilder().addBuilder(
            index, xyz.shiqihao.proto.ProtobufMessage.Message.UserInfo.getDefaultInstance());
      }
      /**
       * <code>repeated .protobuf.Message.UserInfo user_info = 1;</code>
       */
      public java.util.List<xyz.shiqihao.proto.ProtobufMessage.Message.UserInfo.Builder> 
           getUserInfoBuilderList() {
        return getUserInfoFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          xyz.shiqihao.proto.ProtobufMessage.Message.UserInfo, xyz.shiqihao.proto.ProtobufMessage.Message.UserInfo.Builder, xyz.shiqihao.proto.ProtobufMessage.Message.UserInfoOrBuilder> 
          getUserInfoFieldBuilder() {
        if (userInfoBuilder_ == null) {
          userInfoBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              xyz.shiqihao.proto.ProtobufMessage.Message.UserInfo, xyz.shiqihao.proto.ProtobufMessage.Message.UserInfo.Builder, xyz.shiqihao.proto.ProtobufMessage.Message.UserInfoOrBuilder>(
                  userInfo_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          userInfo_ = null;
        }
        return userInfoBuilder_;
      }

      private int smsProvider_ = 0;
      /**
       * <code>.protobuf.Message.SmsProvider sms_provider = 2;</code>
       */
      public int getSmsProviderValue() {
        return smsProvider_;
      }
      /**
       * <code>.protobuf.Message.SmsProvider sms_provider = 2;</code>
       */
      public Builder setSmsProviderValue(int value) {
        smsProvider_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.protobuf.Message.SmsProvider sms_provider = 2;</code>
       */
      public xyz.shiqihao.proto.ProtobufMessage.Message.SmsProvider getSmsProvider() {
        @SuppressWarnings("deprecation")
        xyz.shiqihao.proto.ProtobufMessage.Message.SmsProvider result = xyz.shiqihao.proto.ProtobufMessage.Message.SmsProvider.valueOf(smsProvider_);
        return result == null ? xyz.shiqihao.proto.ProtobufMessage.Message.SmsProvider.UNRECOGNIZED : result;
      }
      /**
       * <code>.protobuf.Message.SmsProvider sms_provider = 2;</code>
       */
      public Builder setSmsProvider(xyz.shiqihao.proto.ProtobufMessage.Message.SmsProvider value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        smsProvider_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.protobuf.Message.SmsProvider sms_provider = 2;</code>
       */
      public Builder clearSmsProvider() {
        
        smsProvider_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object providerKey_ = "";
      /**
       * <code>string provider_key = 3;</code>
       */
      public java.lang.String getProviderKey() {
        java.lang.Object ref = providerKey_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          providerKey_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string provider_key = 3;</code>
       */
      public com.google.protobuf.ByteString
          getProviderKeyBytes() {
        java.lang.Object ref = providerKey_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          providerKey_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string provider_key = 3;</code>
       */
      public Builder setProviderKey(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        providerKey_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string provider_key = 3;</code>
       */
      public Builder clearProviderKey() {
        
        providerKey_ = getDefaultInstance().getProviderKey();
        onChanged();
        return this;
      }
      /**
       * <code>string provider_key = 3;</code>
       */
      public Builder setProviderKeyBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        providerKey_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object providerValue_ = "";
      /**
       * <code>string provider_value = 4;</code>
       */
      public java.lang.String getProviderValue() {
        java.lang.Object ref = providerValue_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          providerValue_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string provider_value = 4;</code>
       */
      public com.google.protobuf.ByteString
          getProviderValueBytes() {
        java.lang.Object ref = providerValue_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          providerValue_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string provider_value = 4;</code>
       */
      public Builder setProviderValue(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        providerValue_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string provider_value = 4;</code>
       */
      public Builder clearProviderValue() {
        
        providerValue_ = getDefaultInstance().getProviderValue();
        onChanged();
        return this;
      }
      /**
       * <code>string provider_value = 4;</code>
       */
      public Builder setProviderValueBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        providerValue_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object signName_ = "";
      /**
       * <code>string sign_name = 5;</code>
       */
      public java.lang.String getSignName() {
        java.lang.Object ref = signName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          signName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string sign_name = 5;</code>
       */
      public com.google.protobuf.ByteString
          getSignNameBytes() {
        java.lang.Object ref = signName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          signName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string sign_name = 5;</code>
       */
      public Builder setSignName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        signName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string sign_name = 5;</code>
       */
      public Builder clearSignName() {
        
        signName_ = getDefaultInstance().getSignName();
        onChanged();
        return this;
      }
      /**
       * <code>string sign_name = 5;</code>
       */
      public Builder setSignNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        signName_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object templateCode_ = "";
      /**
       * <code>string template_code = 6;</code>
       */
      public java.lang.String getTemplateCode() {
        java.lang.Object ref = templateCode_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          templateCode_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string template_code = 6;</code>
       */
      public com.google.protobuf.ByteString
          getTemplateCodeBytes() {
        java.lang.Object ref = templateCode_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          templateCode_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string template_code = 6;</code>
       */
      public Builder setTemplateCode(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        templateCode_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string template_code = 6;</code>
       */
      public Builder clearTemplateCode() {
        
        templateCode_ = getDefaultInstance().getTemplateCode();
        onChanged();
        return this;
      }
      /**
       * <code>string template_code = 6;</code>
       */
      public Builder setTemplateCodeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        templateCode_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object templateContent_ = "";
      /**
       * <code>string template_content = 7;</code>
       */
      public java.lang.String getTemplateContent() {
        java.lang.Object ref = templateContent_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          templateContent_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string template_content = 7;</code>
       */
      public com.google.protobuf.ByteString
          getTemplateContentBytes() {
        java.lang.Object ref = templateContent_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          templateContent_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string template_content = 7;</code>
       */
      public Builder setTemplateContent(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        templateContent_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string template_content = 7;</code>
       */
      public Builder clearTemplateContent() {
        
        templateContent_ = getDefaultInstance().getTemplateContent();
        onChanged();
        return this;
      }
      /**
       * <code>string template_content = 7;</code>
       */
      public Builder setTemplateContentBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        templateContent_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:protobuf.Message)
    }

    // @@protoc_insertion_point(class_scope:protobuf.Message)
    private static final xyz.shiqihao.proto.ProtobufMessage.Message DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new xyz.shiqihao.proto.ProtobufMessage.Message();
    }

    public static xyz.shiqihao.proto.ProtobufMessage.Message getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Message>
        PARSER = new com.google.protobuf.AbstractParser<Message>() {
      @java.lang.Override
      public Message parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Message(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Message> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Message> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public xyz.shiqihao.proto.ProtobufMessage.Message getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protobuf_Message_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protobuf_Message_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protobuf_Message_UserInfo_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protobuf_Message_UserInfo_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\037src/main/protobuf/message.proto\022\010proto" +
      "buf\"\242\002\n\007Message\022-\n\tuser_info\030\001 \003(\0132\032.pro" +
      "tobuf.Message.UserInfo\0223\n\014sms_provider\030\002" +
      " \001(\0162\035.protobuf.Message.SmsProvider\022\024\n\014p" +
      "rovider_key\030\003 \001(\t\022\026\n\016provider_value\030\004 \001(" +
      "\t\022\021\n\tsign_name\030\005 \001(\t\022\025\n\rtemplate_code\030\006 " +
      "\001(\t\022\030\n\020template_content\030\007 \001(\t\032\031\n\010UserInf" +
      "o\022\r\n\005value\030\001 \003(\t\"&\n\013SmsProvider\022\n\n\006ALIYU" +
      "N\020\000\022\013\n\007YUNPIAN\020\001B%\n\022xyz.shiqihao.protoB\017" +
      "ProtobufMessageb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_protobuf_Message_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_protobuf_Message_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protobuf_Message_descriptor,
        new java.lang.String[] { "UserInfo", "SmsProvider", "ProviderKey", "ProviderValue", "SignName", "TemplateCode", "TemplateContent", });
    internal_static_protobuf_Message_UserInfo_descriptor =
      internal_static_protobuf_Message_descriptor.getNestedTypes().get(0);
    internal_static_protobuf_Message_UserInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protobuf_Message_UserInfo_descriptor,
        new java.lang.String[] { "Value", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
